Add pnpm-lock.yaml file
When deploying on fly the build process is complaning about missing
`pnpm-lock.yaml` file

```
Error: failed to fetch an image or build from source: error building: failed to solve: failed to compute cache key: "/pnpm-lock.yaml" not found: not found
```